image: docker:git

stages:
  - test
  - build
  - e2e-test
  - publish

before_script:
  - export DOCKER_REPOSITORY="mendersoftware/gui"
  - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
  - export NODE_ENV=$(echo "$DOCKER_TAG" | grep -Eq '^(staging|production)$' && echo "production" || echo "development")
  - export SERVICE_ENV=$(echo "$DOCKER_TAG" | grep -Eq '^(development|staging|production)$' && echo $DOCKER_TAG || echo "development")
  - export SERVICE_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG
  - export COMMIT_TAG="$CI_COMMIT_REF_SLUG"_"$CI_COMMIT_SHA";

build:
  stage: build
  services:
    - docker:dind
  script:
    - echo "building gui for ${SERVICE_IMAGE}"
    - docker build
      -t $SERVICE_IMAGE
      -t $DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG
      .
    - docker save $SERVICE_IMAGE > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker

test:static:
  stage: test
  before_script:
    - apk add --no-cache bash
    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin
    - git clone http://github.com/mendersoftware/mendertesting
  script:
    - mendertesting/check_commits.sh

test:lint:
  stage: test
  image: node
  script:
    - npm ci
    - npm run lint
  except:
    - master

test:acceptance:
  image: tiangolo/docker-with-compose
  dependencies:
    - build
  services:
    - docker:18-dind
  stage: e2e-test
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:pr
    - apk add git bash
    - git clone https://github.com/mendersoftware/integration.git
    - cp -r integration/tests/* tests
    - GUI_REPOSITORY=$(pwd) INTEGRATION_PATH=$(pwd)/integration ./tests/e2e_tests/run
  tags:
    - mender-qa-slave

test:unit:
  image: node:11.6.0-alpine
  stage: test
  script:
    - npm install
    - npm run test

publish:
  stage: publish
  services:
    - docker:dind
  dependencies:
    - build
    - test:acceptance
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$COMMIT_TAG
    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # - docker push $CI_REGISTRY_IMAGE
  only:
    - master
  tags:
    - docker
